/// # Runtime Environment
///
/// Stores variables and functions defined during execution.

use std::collections::HashMap;
use std::fmt;

/// Vedic Multi-valued Logic (चतुष्कोटि - Chatushkoti)
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum TattvaState {
    /// सत् - Exists / True (Sat)
    Sat,
    /// असत् - Not-exists / False (Asat)
    Asat,
    /// सदसत् - Both exists and not-exists (Sadasat)
    Sadasat,
    /// अव्यक्तम् - Unmanifest / Neither (Avyaktam)
    Avyaktam,
}

/// Runtime Value
#[derive(Debug, Clone)]
pub enum Value {
    /// Integer
    Integer(i64),
    /// Floating point
    Float(f64),
    /// String
    Str(String),
    /// Vedic multi-valued logic
    Tattva(TattvaState),
    /// List / Array
    List(Vec<Value>),
    /// Dictionary (key-value map)
    Dict(HashMap<String, Value>),
    /// शून्य — Emptiness / Null
    Shunya,
    /// Function / Named Sutra
    Function {
        name: String,
        params: Vec<String>,
        /// Stored as source text for deferred execution
        body_source: String,
    },
    /// Custom data template (Swaroopa)
    StructInstance {
        name: String,
        fields: HashMap<String, Value>,
    },
    /// Lambda / Anonymous function (विद्युत्)
    Lambda {
        params: Vec<String>,
        body: Vec<crate::parser::ast::Statement>,
    },
    /// Digital Asset Token generated by Unadi Engine
    Asset(crate::vyakarana::AssetToken),
}

impl Value {
    pub fn is_truthy(&self) -> bool {
        match self {
            Value::Tattva(t) => *t == TattvaState::Sat || *t == TattvaState::Sadasat,
            Value::Integer(n) => *n != 0,
            Value::Float(n) => *n != 0.0,
            Value::Str(s) => !s.is_empty(),
            Value::List(l) => !l.is_empty(),
            Value::Dict(d) => !d.is_empty(),
            Value::Shunya => false,
            Value::Function { .. } => true,
            Value::StructInstance { .. } => true,
            Value::Lambda { .. } => true,
            Value::Asset(_) => true,
        }
    }

    pub fn type_name(&self) -> &'static str {
        match self {
            Value::Integer(_) => "पूर्णाङ्क",
            Value::Float(_) => "दशमलव",
            Value::Str(_) => "वाक्य",
            Value::Tattva(_) => "तत्त्व",
            Value::List(_) => "सूची",
            Value::Dict(_) => "कोश",
            Value::Shunya => "शून्य",
            Value::Function { .. } => "सूत्र",
            Value::StructInstance { .. } => "स्वरूप",
            Value::Lambda { .. } => "विद्युत्",
            Value::Asset(_) => "सम्पत्ति",
        }
    }
}

impl fmt::Display for Value {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Value::Integer(n) => write!(f, "{}", n),
            Value::Float(n) => write!(f, "{}", n),
            Value::Str(s) => write!(f, "{}", s),
            Value::Tattva(t) => write!(f, "{}", match t {
                TattvaState::Sat => "सत्",
                TattvaState::Asat => "असत्",
                TattvaState::Sadasat => "सदसत्",
                TattvaState::Avyaktam => "अव्यक्तम्",
            }),
            Value::List(items) => {
                write!(f, "[")?;
                for (i, item) in items.iter().enumerate() {
                    if i > 0 { write!(f, ", ")?; }
                    write!(f, "{}", item)?;
                }
                write!(f, "]")
            }
            Value::Dict(map) => {
                write!(f, "{{")?;
                for (i, (k, v)) in map.iter().enumerate() {
                    if i > 0 { write!(f, ", ")?; }
                    write!(f, "\"{}\": {}", k, v)?;
                }
                write!(f, "}}")
            }
            Value::Shunya => write!(f, "शून्य"),
            Value::Function { name, .. } => write!(f, "<सूत्र {}>", name),
            Value::StructInstance { name, fields } => {
                write!(f, "{}(", name)?;
                for (i, (k, v)) in fields.iter().enumerate() {
                    if i > 0 { write!(f, ", ")?; }
                    write!(f, "{}: {}", k, v)?;
                }
                write!(f, ")")
            }
            Value::Lambda { params, .. } => write!(f, "<विद्युत्({})>", params.join(", ")),
            Value::Asset(asset) => write!(f, "[Asset: {} (Root: {} + {}) | Value: {}]", asset.derived_asset, asset.root_action, asset.suffix, asset.value),
        }
    }
}

/// पद (Pada - Word/Token) representing a bound variable in the Vritti sequence
#[derive(Clone, Debug)]
pub struct Pada {
    pub name: String,
    pub value: Value,
    // Add grammatical tags here in the future
}

/// Runtime Environment — Variable Storage (Vritti Memory Model)
#[derive(Clone)]
pub struct Environment {
    /// The continuous cosmic ribbon of memory
    pub vritti: Vec<Pada>,
    /// Scope boundary markers (indices marking where each scope begins)
    scope_markers: Vec<usize>,
}

impl Environment {
    pub fn new() -> Self {
        let mut env = Self {
            vritti: Vec::new(),
            scope_markers: Vec::new(),
        };
        env.define("शून्य", Value::Shunya);
        env
    }

    pub fn define(&mut self, name: impl Into<String>, value: Value) {
        self.vritti.push(Pada {
            name: name.into(),
            value,
        });
    }

    pub fn get(&self, name: &str) -> Option<&Value> {
        // Pratyahara-style backward scanning: search the ribbon from present to past
        for pada in self.vritti.iter().rev() {
            if pada.name == name {
                return Some(&pada.value);
            }
        }
        None
    }

    pub fn set(&mut self, name: &str, value: Value) -> bool {
        // In the Vritti paradigm, we do not mutate the past.
        // We append a new Adesha (substitute manifestation) to the ribbon.
        // We still check if it existed to fulfill the contract of 'set' vs 'define',
        // but physically it's an append.
        let mut exists = false;
        for pada in self.vritti.iter().rev() {
            if pada.name == name {
                exists = true;
                break;
            }
        }
        
        if exists {
            self.vritti.push(Pada {
                name: name.to_string(),
                value,
            });
            return true;
        }
        
        false
    }

    pub fn push_scope(&mut self) {
        self.scope_markers.push(self.vritti.len());
    }

    pub fn pop_scope(&mut self) {
        // Lopa (लोप) - Erasing the transient states when scope ends
        if let Some(marker) = self.scope_markers.pop() {
            self.vritti.truncate(marker);
        }
    }
}

impl Default for Environment {
    fn default() -> Self { Self::new() }
}
